#!/usr/bin/env bash
set -euo pipefail

RCLOCAL="/etc/rc.local"

# ---------- helpers ----------
require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "Please run with sudo:"
    echo "  sudo bash install.sh"
    exit 1
  fi
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1"; exit 1; }
}

pause() { read -r -p "Press Enter to continue..." _ || true; }

is_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS='.' read -r a b c d <<<"$ip"
  for n in "$a" "$b" "$c" "$d"; do
    [[ "$n" -ge 0 && "$n" -le 255 ]] || return 1
  done
  return 0
}

ask_ipv4() {
  local prompt="$1"
  local ip=""
  while true; do
    read -r -p "$prompt " ip
    if is_ipv4 "$ip"; then
      echo "$ip"
      return 0
    fi
    echo "Invalid IPv4. Try again."
  done
}

ask_int() {
  local prompt="$1"
  local min="$2"
  local max="$3"
  local val=""
  while true; do
    read -r -p "$prompt " val
    if [[ "$val" =~ ^[0-9]+$ ]] && [[ "$val" -ge "$min" ]] && [[ "$val" -le "$max" ]]; then
      echo "$val"
      return 0
    fi
    echo "Invalid number. Allowed: $min-$max"
  done
}

enable_rc_local_service_if_needed() {
  # Some Ubuntu versions don't enable rc.local by default.
  if [[ ! -f "$RCLOCAL" ]]; then
    cat > "$RCLOCAL" <<'EOF'
#!/bin/bash
exit 0
EOF
    chmod +x "$RCLOCAL"
  fi

  if ! systemctl list-unit-files | grep -q '^rc-local.service'; then
    cat > /etc/systemd/system/rc-local.service <<'EOF'
[Unit]
Description=/etc/rc.local Compatibility
After=network-online.target
Wants=network-online.target

[Service]
Type=forking
ExecStart=/etc/rc.local start
TimeoutSec=0
RemainAfterExit=yes
GuessMainPID=no

[Install]
WantedBy=multi-user.target
EOF
    systemctl daemon-reload
    systemctl enable --now rc-local.service >/dev/null 2>&1 || true
  else
    systemctl enable --now rc-local.service >/dev/null 2>&1 || true
  fi
}

backup_rc_local() {
  if [[ -f "$RCLOCAL" ]]; then
    cp -f "$RCLOCAL" "${RCLOCAL}.bak.$(date +%Y%m%d-%H%M%S)"
  fi
}

# We will generate a complete rc.local content each time for simplicity.
write_rc_local_header() {
  cat > "$RCLOCAL" <<'EOF'
#!/bin/bash
# Generated by install.sh (GRE rclocal)
EOF
}

write_rc_local_footer() {
  cat >> "$RCLOCAL" <<'EOF'

exit 0
EOF
  chmod +x "$RCLOCAL"
}

run_rc_local_now() {
  # Run now (as user requested style)
  sudo bash /etc/rc.local || true
}

# ---------- GRE config generation ----------
# Addressing:
# For IRAN[k] tunnel:
#   IRAN main: 10.10.k.1/30   (peer 10.10.k.2)
# Additional IP blocks (count N):
#   block j (1..N): IRAN=10.10.k.(4*j+1)/30   peer=10.10.k.(4*j+2)
# Example for k=1:
#   main  : 10.10.1.1/30 <-> 10.10.1.2/30
#   add #1: 10.10.1.5/30 <-> 10.10.1.6/30
#   add #2: 10.10.1.9/30 <-> 10.10.1.10/30
#
# Note: This avoids overlap with /30 math.

append_iran_tunnel_to_rc_local() {
  local k="$1" iran_ip="$2" kharej_ip="$3" mtu="$4" add_count="$5"
  local ifname="gre${k}"

  # IRAN side: remote=kharej local=iran
  cat >> "$RCLOCAL" <<EOF

# ---- IRAN[$k] ----
sudo ip tunnel add ${ifname} mode gre remote ${kharej_ip} local ${iran_ip} ttl 255
sudo ip link set ${ifname} mtu ${mtu}
sudo ip link set ${ifname} up
sudo ip addr add 10.10.${k}.1/30 dev ${ifname}
EOF

  # Additional /30 blocks on same GRE interface
  if [[ "$add_count" -gt 0 ]]; then
    local j
    for ((j=1; j<=add_count; j++)); do
      local host=$((4*j+1))
      cat >> "$RCLOCAL" <<EOF
sudo ip addr add 10.10.${k}.${host}/30 dev ${ifname}
EOF
    done
  fi

  cat >> "$RCLOCAL" <<EOF
nohup ping 10.10.${k}.2 >/dev/null 2>&1 &
EOF
}

append_kharej_tunnel_to_rc_local() {
  local k="$1" kharej_ip="$2" iran_ip="$3" mtu="$4" add_count="$5"
  local ifname="gre${k}"

  # KHAREJ side: remote=iran local=kharej
  cat >> "$RCLOCAL" <<EOF

# ---- KHAREJ <-> IRAN[$k] ----
sudo ip tunnel add ${ifname} mode gre remote ${iran_ip} local ${kharej_ip} ttl 255
sudo ip link set ${ifname} mtu ${mtu}
sudo ip link set ${ifname} up
sudo ip addr add 10.10.${k}.2/30 dev ${ifname}
EOF

  if [[ "$add_count" -gt 0 ]]; then
    local j
    for ((j=1; j<=add_count; j++)); do
      local host=$((4*j+2))
      cat >> "$RCLOCAL" <<EOF
sudo ip addr add 10.10.${k}.${host}/30 dev ${ifname}
EOF
    done
  fi

  cat >> "$RCLOCAL" <<EOF
nohup ping 10.10.${k}.1 >/dev/null 2>&1 &
EOF
}

ask_mtu() {
  local ans mtu
  read -r -p "Do you want to set the MTU [GRE6]? (yes/no): " ans
  if [[ "$ans" =~ ^([Yy][Ee][Ss]|[Yy])$ ]]; then
    mtu="$(ask_int "Enter MTU value (e.g. 1420):" 1200 1500)"
    echo "$mtu"
  else
    echo "1420"
  fi
}

# ---------- Menus ----------
menu_main() {
  while true; do
    clear || true
    echo "1-Multiple Servers Menu [1]KHAREJ [10]IRAN"
    echo "2-Remove (local)"
    echo
    local sel
    sel="$(ask_int "Select:" 1 2)"
    case "$sel" in
      1) menu_multiple_servers ;;
      2) menu_remove ;;
    esac
  done
}

menu_multiple_servers() {
  clear || true
  echo "1-GRE rclocal"
  echo
  local sel
  sel="$(ask_int "Select:" 1 1)"
  case "$sel" in
    1) menu_choose_what_to_do ;;
  esac
}

menu_choose_what_to_do() {
  while true; do
    clear || true
    echo "Choose what to do:"
    echo "1. IRAN[1]"
    echo "2. IRAN[2]"
    echo "3. IRAN[3]"
    echo "4. IRAN[4]"
    echo "5. IRAN[5]"
    echo "6. IRAN[6]"
    echo "7. IRAN[7]"
    echo "8. IRAN[8]"
    echo "9. IRAN[9]"
    echo "10. IRAN[10]"
    echo "───────────────────────────────────────"
    echo "11. Kharej"
    echo
    local sel
    sel="$(ask_int "Select:" 1 11)"
    if [[ "$sel" -eq 11 ]]; then
      flow_kharej
      return
    else
      flow_iran "$sel"
      return
    fi
  done
}

flow_iran() {
  local k="$1"
  clear || true

  local iran_ip kharej_ip add_count mtu
  iran_ip="$(ask_ipv4 "Enter IRAN [${k}] IPV4 address:")"
  kharej_ip="$(ask_ipv4 "Enter Kharej IPV4 address:")"
  add_count="$(ask_int "Enter the number of additional IPs for the GRE tunnel:" 0 50)"
  mtu="$(ask_mtu)"

  echo "[*] Writing /etc/rc.local ..."
  enable_rc_local_service_if_needed
  backup_rc_local
  write_rc_local_header

  append_iran_tunnel_to_rc_local "$k" "$iran_ip" "$kharej_ip" "$mtu" "$add_count"

  write_rc_local_footer

  echo "[*] Applying now..."
  run_rc_local_now

  echo
  echo "Done."
  echo "IRAN[$k] main: 10.10.${k}.1/30"
  echo "KHAREJ peer:  10.10.${k}.2/30"
  echo "To remove local:"
  echo "  sudo ip link set gre${k} down"
  echo "  sudo ip tunnel del gre${k}"
  echo
  pause
}

flow_kharej() {
  clear || true

  local how_many
  how_many="$(ask_int "How many IRAN Servers do you have?" 1 10)"

  enable_rc_local_service_if_needed
  backup_rc_local
  write_rc_local_header

  local i
  for ((i=1; i<=how_many; i++)); do
    clear || true
    echo "Configuring IRAN[$i] on KHAREJ..."
    local kharej_ip iran_ip add_count mtu
    kharej_ip="$(ask_ipv4 "Enter Kharej IPV4 address:")"
    iran_ip="$(ask_ipv4 "Enter IRAN [${i}] IPV4 address:")"
    add_count="$(ask_int "Enter the number of additional IPs for the GRE6 tunnel:" 0 50)"
    mtu="$(ask_mtu)"

    append_kharej_tunnel_to_rc_local "$i" "$kharej_ip" "$iran_ip" "$mtu" "$add_count"
  done

  write_rc_local_footer

  echo "[*] Applying now..."
  run_rc_local_now

  echo
  echo "Done."
  echo "To remove local (example gre1):"
  echo "  sudo ip link set gre1 down"
  echo "  sudo ip tunnel del gre1"
  echo
  pause
}

menu_remove() {
  while true; do
    clear || true
    echo "Remove (local)"
    echo "1) Remove one tunnel (greX)"
    echo "2) Remove gre1..gre10"
    echo "3) Back"
    echo
    local sel
    sel="$(ask_int "Select:" 1 3)"
    case "$sel" in
      1)
        local x
        x="$(ask_int "Enter X for greX:" 1 50)"
        sudo ip link set "gre${x}" down >/dev/null 2>&1 || true
        sudo ip tunnel del "gre${x}" >/dev/null 2>&1 || true
        echo "Removed gre${x} (if existed)."
        pause
        ;;
      2)
        local i
        for i in {1..10}; do
          sudo ip link set "gre${i}" down >/dev/null 2>&1 || true
          sudo ip tunnel del "gre${i}" >/dev/null 2>&1 || true
        done
        echo "Removed gre1..gre10 (if existed)."
        pause
        ;;
      3) return ;;
    esac
  done
}

# ---------- main ----------
main() {
  require_root
  need_cmd ip
  need_cmd systemctl

  menu_main
}

main "$@"
