#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# GRE Tunnel Installer/Remover (Ubuntu)
# - IRAN side: creates ONE GRE tunnel gre<iran_no> to foreign server
# - KHAREJ side: can create MULTIPLE GRE tunnels gre1..greN to multiple IRAN servers
#
# Addressing scheme:
#   IRAN i  : 10.10.i.1/30
#   KHAREJ i: 10.10.i.2/30
#
# Also supports FULL local removal:
#   - delete GRE interfaces
#   - remove persistent systemd service + script
# ============================================================

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    echo "[-] Please run as root: sudo bash install.sh"
    exit 1
  fi
}

need_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "[-] Missing command: $1"
    exit 1
  }
}

is_ipv4() {
  local ip="$1"
  [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1
  IFS='.' read -r a b c d <<<"$ip"
  for n in "$a" "$b" "$c" "$d"; do
    [[ "$n" -ge 0 && "$n" -le 255 ]] || return 1
  done
  return 0
}

ask_ipv4() {
  local prompt="$1"
  local ip=""
  while true; do
    read -r -p "${prompt}: " ip
    if is_ipv4 "$ip"; then
      echo "$ip"
      return 0
    fi
    echo "[-] Invalid IPv4. Try again."
  done
}

ask_int_range() {
  local prompt="$1"
  local min="$2"
  local max="$3"
  local val=""
  while true; do
    read -r -p "${prompt}: " val
    if [[ "$val" =~ ^[0-9]+$ ]] && [[ "$val" -ge "$min" ]] && [[ "$val" -le "$max" ]]; then
      echo "$val"
      return 0
    fi
    echo "[-] Invalid number. Allowed range: ${min}-${max}"
  done
}

ensure_sysctl_forwarding() {
  echo "[*] Enabling net.ipv4.ip_forward=1"
  sysctl -w net.ipv4.ip_forward=1 >/dev/null
  echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-gre.conf
  sysctl --system >/dev/null || true
}

create_tunnel_now() {
  local ifname="$1"
  local remote_pub="$2"
  local local_pub="$3"
  local mtu="$4"
  local addr_cidr="$5"

  if ip link show "$ifname" >/dev/null 2>&1; then
    echo "[*] $ifname exists, recreating..."
    ip link set "$ifname" down || true
    ip tunnel del "$ifname" || true
  fi

  echo "[*] Creating $ifname (local=$local_pub, remote=$remote_pub, addr=$addr_cidr)"
  ip tunnel add "$ifname" mode gre remote "$remote_pub" local "$local_pub" ttl 255
  ip link set "$ifname" mtu "$mtu"
  ip link set "$ifname" up
  ip addr add "$addr_cidr" dev "$ifname"
}

delete_tunnel_now() {
  local ifname="$1"
  if ip link show "$ifname" >/dev/null 2>&1; then
    echo "[*] Deleting $ifname ..."
    ip link set "$ifname" down || true
    ip tunnel del "$ifname" || true
  else
    echo "[!] $ifname not found (skipped)"
  fi
}

SERVICE_PATH="/etc/systemd/system/gre-tunnels.service"
SCRIPT_PATH="/usr/local/sbin/gre-tunnels-up.sh"

write_systemd_unit_and_script_header() {
  echo "[*] Creating persistent script: $SCRIPT_PATH"
  cat > "$SCRIPT_PATH" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
# Generated by install.sh — brings up configured GRE tunnels

EOF
  chmod +x "$SCRIPT_PATH"

  echo "[*] Creating systemd service: $SERVICE_PATH"
  cat > "$SERVICE_PATH" <<EOF
[Unit]
Description=Bring up GRE tunnels
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
ExecStart=$SCRIPT_PATH
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
EOF

  systemctl daemon-reload
  systemctl enable --now gre-tunnels.service >/dev/null
}

append_persistent_lines_for_tunnel() {
  local ifname="$1"
  local remote_pub="$2"
  local local_pub="$3"
  local mtu="$4"
  local addr_cidr="$5"

  {
    echo "ip tunnel add ${ifname} mode gre remote ${remote_pub} local ${local_pub} ttl 255"
    echo "ip link set ${ifname} mtu ${mtu}"
    echo "ip link set ${ifname} up"
    echo "ip addr add ${addr_cidr} dev ${ifname}"
    echo ""
  } >> "$SCRIPT_PATH"
}

remove_persistence() {
  echo "[*] Removing persistence (systemd + script)..."
  if systemctl list-unit-files | grep -q '^gre-tunnels.service'; then
    systemctl disable --now gre-tunnels.service >/dev/null 2>&1 || true
  fi
  rm -f "$SCRIPT_PATH" "$SERVICE_PATH"
  systemctl daemon-reload
  echo "[OK] Persistence removed."
}

install_flow() {
  echo "----------------------------------------"
  echo "1) UBUNTU IRAN (create 1 tunnel)"
  echo "2) UBUNTU KHAREJ (create multiple tunnels)"
  echo "----------------------------------------"
  local role
  role="$(ask_int_range "Select role (1=IRAN, 2=KHAREJ)" 1 2)"

  local mtu="1420"
  read -r -p "MTU (default 1420) Enter to keep, or type a number: " mtu_in || true
  if [[ -n "${mtu_in:-}" ]] && [[ "$mtu_in" =~ ^[0-9]+$ ]] && [[ "$mtu_in" -ge 1200 ]] && [[ "$mtu_in" -le 1500 ]]; then
    mtu="$mtu_in"
  fi

  local local_pub
  local_pub="$(ask_ipv4 "Enter THIS server public IPv4 (local)")"

  write_systemd_unit_and_script_header

  read -r -p "Enable IPv4 forwarding? (y/n) [y]: " fw || true
  fw="${fw:-y}"
  if [[ "$fw" =~ ^[Yy]$ ]]; then
    ensure_sysctl_forwarding
  fi

  if [[ "$role" -eq 1 ]]; then
    local iran_no
    iran_no="$(ask_int_range "Enter IRAN node number (e.g. 1)" 1 250)"
    local remote_pub
    remote_pub="$(ask_ipv4 "Enter KHAREJ public IPv4 (remote)")"

    local ifname="gre${iran_no}"
    local addr="10.10.${iran_no}.1/30"

    append_persistent_lines_for_tunnel "$ifname" "$remote_pub" "$local_pub" "$mtu" "$addr"
    create_tunnel_now "$ifname" "$remote_pub" "$local_pub" "$mtu" "$addr"

    echo "----------------------------------------"
    echo "[OK] IRAN #${iran_no} configured"
    echo "Interface: ${ifname}"
    echo "IRAN IPv4 : ${addr}"
    echo "Peer IPv4 : 10.10.${iran_no}.2/30"
    echo "Test      : ping -c 5 10.10.${iran_no}.2"
    echo "----------------------------------------"

  else
    local count
    count="$(ask_int_range "How many IRAN servers to connect?" 1 50)"

    local i
    for ((i=1; i<=count; i++)); do
      echo "----------------------------------------"
      echo "IRAN server #${i}"
      local remote_pub
      remote_pub="$(ask_ipv4 "Enter IRAN #${i} public IPv4 (remote)")"

      local ifname="gre${i}"
      local addr="10.10.${i}.2/30"

      append_persistent_lines_for_tunnel "$ifname" "$remote_pub" "$local_pub" "$mtu" "$addr"
      create_tunnel_now "$ifname" "$remote_pub" "$local_pub" "$mtu" "$addr"

      echo "[OK] Created ${ifname} => ${addr} (peer: 10.10.${i}.1/30)"
      echo "Test: ping -c 3 10.10.${i}.1"
    done

    echo "----------------------------------------"
    echo "[OK] All tunnels created on KHAREJ."
    echo "----------------------------------------"
  fi

  echo "[*] Service status: systemctl status gre-tunnels.service --no-pager"
  echo "[*] Persistent script: $SCRIPT_PATH"
}

remove_flow() {
  echo "----------------------------------------"
  echo "REMOVE LOCAL GRE TUNNELS"
  echo "----------------------------------------"
  echo "1) Remove ONE tunnel (greX)"
  echo "2) Remove MANY tunnels (gre1..greN)"
  echo "3) Remove persistence ONLY (systemd + script)"
  echo "4) Remove EVERYTHING (tunnels + persistence)"
  echo "----------------------------------------"
  local opt
  opt="$(ask_int_range "Select option" 1 4)"

  case "$opt" in
    1)
      local n
      n="$(ask_int_range "Enter tunnel number X for greX" 1 250)"
      delete_tunnel_now "gre${n}"
      ;;
    2)
      local n
      n="$(ask_int_range "Enter N for removing gre1..greN" 1 250)"
      local i
      for ((i=1; i<=n; i++)); do
        delete_tunnel_now "gre${i}"
      done
      ;;
    3)
      remove_persistence
      ;;
    4)
      # remove all gre* found
      echo "[*] Removing all gre* interfaces found..."
      while read -r ifname; do
        [[ -n "$ifname" ]] && delete_tunnel_now "$ifname"
      done < <(ip -o link show | awk -F': ' '{print $2}' | grep -E '^gre[0-9]+$' || true)

      remove_persistence
      ;;
  esac

  echo "[OK] Done."
}

main() {
  require_root
  need_cmd ip
  need_cmd sysctl
  need_cmd systemctl

  echo "========================================"
  echo " GRE Tunnel Installer / Remover (Ubuntu)"
  echo "========================================"
  echo "1) Install / Configure"
  echo "2) Remove (local)"
  echo "========================================"
  local top
  top="$(ask_int_range "Select" 1 2)"

  if [[ "$top" -eq 1 ]]; then
    install_flow
  else
    remove_flow
  fi
}

main "$@"
